src/authz/models/Z1role.php
<?php

namespace myzero1\authz\authz\models;

use Yii;

/**
 * This is the model class for table "z1role".
 *
 * @property int $id
 * @property string $name
 * @property string $des
 * @property string $permissions
 * @property int $status
 * @property int $created_at
 * @property int $updated_at
 * @property int $deleted_at
 */
class Z1role extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'z1role';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['name', 'des', 'permissions', 'created_at', 'updated_at'], 'required'],
            [['permissions'], 'string'],
            [['status', 'created_at', 'updated_at', 'deleted_at'], 'integer'],
            [['name', 'des'], 'string', 'max' => 255],
            [['name'], 'unique'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'des' => 'Des',
            'permissions' => 'Permissions',
            'status' => 'Status',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'deleted_at' => 'Deleted At',
        ];
    }

    /**
     * {@inheritdoc}
     */
    static public function roleList()
    {
        $result=self::find()->select(['id','name'])->where(['and',['=','deleted_at',0]])->all();
        $roles=array_combine(array_column($result,'id'),array_column($result,'name'));

        return $roles;
    }
}

src/authz/controllers/UserController.php
<?php

namespace myzero1\authz\authz\controllers;

use myzero1\authz\authz\models\User;
use myzero1\authz\authz\models\search\UserSearcher;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * Z1roleController implements the CRUD actions for User model.
 */
class UserController extends Controller
{
    /**
     * @inheritDoc
     */
    public function behaviors()
    {
        return array_merge(
            parent::behaviors(),
            [
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['POST'],
                    ],
                ],
            ]
        );
    }

    /**
     * Lists all User models.
     *
     * @return string
     */
    public function actionIndex()
    {
        $searchModel = new UserSearcher();
        $dataProvider = $searchModel->search($this->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single User model.
     * @param int $id ID
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string|\yii\web\Response
     */
    public function actionCreate()
    {
        $model = new User();
        
        if ($this->request->isPost) {
            $post=$this->request->post();
            $post['User']['created_at']=$post['User']['updated_at']=time();
            $post['User']['auth_key']=$post['User']['username'];
            $post['User']['password_hash']=\Yii::$app->security->generatePasswordHash($post['User']['password']);
            
            if ($model->load($post) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            }
        } else {
            $model->loadDefaultValues();
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $id ID
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $model->password='myzero1_password_placeholder';

        if ($this->request->isPost && $model->load($this->request->post())) {
            if ($model->password=='myzero1_password_placeholder') {
                $model->password_hash=\Yii::$app->security->generatePasswordHash($model->password);
            }
            
            if ($model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            }
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing User model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param int $id ID
     * @return \yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param int $id ID
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = User::findOne(['id' => $id])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

src/authz/controllers/Z1roleController.php
<?php

namespace myzero1\authz\authz\controllers;

use myzero1\authz\authz\models\Z1role;
use myzero1\authz\authz\models\search\Z1roleSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * Z1roleController implements the CRUD actions for User model.
 */
class Z1roleController extends Controller
{
    /**
     * @inheritDoc
     */
    public function behaviors()
    {
        return array_merge(
            parent::behaviors(),
            [
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['POST'],
                    ],
                ],
            ]
        );
    }

    /**
     * Lists all User models.
     *
     * @return string
     */
    public function actionIndex()
    {
        $searchModel = new Z1roleSearch();
        $dataProvider = $searchModel->search($this->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single User model.
     * @param int $id ID
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string|\yii\web\Response
     */
    public function actionCreate()
    {
        $model = new Z1role();
        
        if ($this->request->isPost) {
            $post=$this->request->post();
            $post['Z1role']['created_at']=$post['Z1role']['updated_at']=time();
            
            if ($model->load($post) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            }
        } else {
            $model->loadDefaultValues();
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $id ID
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($this->request->isPost && $model->load($this->request->post()) && $model->save()) {
            // return $this->redirect(['view', 'id' => $model->id]);
            return $this->redirect(['index']);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing User model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param int $id ID
     * @return \yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        // $this->findModel($id)->delete();
        $model = $this->findModel($id);
        $model->deleted_at = time();
        $model->save();

        return $this->redirect(['index']);
    }

    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param int $id ID
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Z1role::find()->where(['id' => $id,'deleted_at' => 0,])->one()) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

src/authz/views/z1role/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model myzero1\authz\authz\models\Z1role */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="z1role-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'des')->textInput(['maxlength' => true]) ?>

    <!-- <?= $form->field($model, 'permissions')->textarea(['rows' => 6]) ?> -->
    <?php
        $accessControl=new myzero1\authz\filters\AccessControl();
        $nodes=$accessControl->ztreePermission();
        $permissions=explode(',',$model->permissions);

        foreach ($nodes as $k => $v) {
            if (in_array($v['id'],$permissions)) {
                $nodes[$k]['checked']=true;
            }
        }

        echo $form->field($model, 'permissions')->hiddenInput()->widget(
            \mallka\ztree\Ztree::class,
            [
                'data'=>$nodes,
                'checkbox'=>true,
            ]
        );

    ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

<style>
    #z1role-permissions-ztree{
        border: solid 1px #ccc;
        border-radius: 4px;
        padding: 10px;
    }
</style>

src/authz/views/z1role/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/** @var yii\web\View $this */
/** @var myzero1\authz\authz\models\search\Z1roleSearch $model */
/** @var yii\widgets\ActiveForm $form */
?>

<div class="user-search search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'name')->label('')->textInput(['placeholder'=>'name']) ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
        <?= Html::a('Create Z1role', ['create'], ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

<style>
    .search{
        overflow: hidden;
    }
    .form-group{
        float: left;
        margin-right: 10px;
    }
    .form-group label{
        display: none;
    }
</style>

src/authz/views/z1role/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model myzero1\authz\authz\models\Z1role */

$this->title = 'Create Z1role';
$this->params['breadcrumbs'][] = ['label' => 'Z1roles', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="z1role-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

src/authz/views/z1role/index.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel myzero1\authz\authz\models\search\Z1roleSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Z1roles';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="z1role-index">

    <?= Html::a('Go Users', ['user/index'], ['class' => 'btn btn-success']) ?>
    &nbsp;&nbsp;
    <?= Html::a('Go Z1role', ['z1role/index'], ['class' => 'btn btn-success']) ?>

    <h1><?= Html::encode($this->title) ?></h1>
    <br/>

    <?php echo $this->render('_search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        // 'filterModel' => $searchModel,
        'columns' => [
            // ['class' => 'yii\grid\SerialColumn'],

            'id',
            'name',
            'des',
            // 'permissions:ntext',
            // 'status',
            //'created_at',
            //'updated_at',
            //'deleted_at',

            'created_at'=>[
                'label' => 'created_at',
                'attribute' => 'created_at',
                'value' => function($row){
                    return \myzero1\authz\helpers\Helper::time2string($row['created_at']);
                }
            ],
            'updated_at'=>[
                'label' => 'updated_at',
                'attribute' => 'updated_at',
                'value' => function($row){
                    return \myzero1\authz\helpers\Helper::time2string($row['updated_at']);
                }
            ],
            [
                'header' => 'operations',
                'class' => yii\grid\ActionColumn::className(),
                // 'template' => '{view} {update} {delete}',
                'template' => '{view}&nbsp;&nbsp;&nbsp;&nbsp;{update}&nbsp;&nbsp;&nbsp;&nbsp;{delete}',
                'urlCreator' => function ($action, $model, $key, $index, $column) {
                    return Url::toRoute([$action, 'id' => $model->id]);
                 }
            ],
        ],
    ]); ?>


</div>

src/authz/views/z1role/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model myzero1\authz\authz\models\Z1role */

$this->title = 'Update Z1role: ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Z1roles', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="z1role-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

src/authz/views/z1role/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model myzero1\authz\authz\models\Z1role */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Z1roles', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="z1role-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'name',
            'des',
            'permissions:ntext',
            'status',
            'created_at'=>[
                'label' => 'created_at',
                'attribute' => 'created_at',
                'value' => function($row){
                    return \myzero1\authz\helpers\Helper::time2string($row['created_at']);
                }
            ],
            'updated_at'=>[
                'label' => 'updated_at',
                'attribute' => 'updated_at',
                'value' => function($row){
                    return \myzero1\authz\helpers\Helper::time2string($row['updated_at']);
                }
            ],
            'deleted_at'=>[
                'label' => 'deleted_at',
                'attribute' => 'deleted_at',
                'value' => function($row){
                    return \myzero1\authz\helpers\Helper::time2string($row['deleted_at']);
                }
            ],
        ],
    ]) ?>

</div>